pipeline {
    agent {
        docker {
            image 'maven:3.8.1-adoptopenjdk-11'
            args '-v /root/.m2:/root/.m2'
        }
    }

    environment {
        REPO_URL = 'https://github.com/DevopsUtn/devopsutn.git'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/tp3' ]], extensions: [],  url: "${REPO_URL}"])
            }
        }
        stage('Build') {
            steps {
                script {
                    echo "Building..."
                    sh(returnStdout: true, script: './mvnw clean compile')
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    echo "Testing..."
                    sh(returnStdout: true, script: './mvnw test')
                }
            }
        }
        stage('Deploy') {
            when { tag 'v*' }
            steps {
                echo "Deploying..."
                sh(returnStdout: true, script: './mvnw install')
            }
        }
    }
}
